import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GominashiHeader />
        {children}
        <GominashiFooter />
      </body>
    </html>
  );
}

const GominashiHeader = () => (
  <header className="bg-gray-800 text-white py-4">
    <div className="container mx-auto flex justify-between items-center">
      <h1 className="text-2xl font-semibold">Gominashi</h1>

      <nav className="space-x-4">
        <a href="#" className="text-white hover:text-gray-300">
          Home
        </a>
        <a href="#" className="text-white hover:text-gray-300">
          About
        </a>
        <a href="#" className="text-white hover:text-gray-300">
          Services
        </a>
        <a href="#" className="text-white hover:text-gray-300">
          Contact
        </a>
      </nav>
    </div>
  </header>
);

const GominashiFooter = () => (
  <footer className="bg-gray-800 text-white py-4">
    <div className="container mx-auto text-center">
      &copy; {new Date().getFullYear()} Gominashi. All rights reserved.
    </div>
  </footer>
);
